### ISSUE TITLE
Check for updated route / run conditions

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker-ios-client#20] opened 2017-02-03 23:15 UTC
In using the App, there are minor issues in keeping 'current' with the state of the schedule and trolley.

The driver often starts the app when warming up the trolley to confirm that the beacon works.  If he starts the app before I disclose the route (at start time - 5 minutes), nothing is shown.   So he calls dispatch to see if it can be fixed.    But the real issue is that after the route takes effect later, the app never shows the route or the trolley position because it stays in the "not tracking any trolley" state.    Terminating the app and restarting it gets everything back in sync.     Regular riders could also experience this problem if they start checking before the route begins.    (The driver could check on DbVisualizer to get the real state, but it's hard to get that link out to them.   Maybe a secret 'driver' Easter egg in the app to send them to that link?)

Routes now frequently change during a single day, for example "The Well" is served separately at opening and closing times.  There will be 9 route changes on Saturday.   Changes can happen on the 1/4 hour.

Possible solution:    If > 15 minutes have elapsed since last open, or if the time has crossed the 1/4 hour since the last open, or if the app is open and passes the 1/4 hour, check for new set of routes / stops.

**Comment by ajhodges** [comment] 2017-02-04 00:12
For what it's worth, I've implemented something like what you described in the Android app and it seems to work well enough (haven't heard any complaints).

Every 1/2 hour the app (if open) forces a schedule update.
https://github.com/codeforgreenville/trolley-tracker-android-client/blob/master/app/src/main/java/com/codeforgvl/trolleytrackerclient/fragments/TrackerFragment.java#L145

When opening the app (and it is not a fresh start), we check again if the last update was >30 mins. If it was, it refreshes.
https://github.com/codeforgreenville/trolley-tracker-android-client/blob/master/app/src/main/java/com/codeforgvl/trolleytrackerclient/helpers/RouteManager.java#L67

Should I change the android update threshold to 15 min? And I can add the "time has crossed the 1/4 hour since last open" case as well if you think it's needed. (sorry to hijack the iOS issue)

**Comment by bikeoid** [comment] 2017-02-04 23:09
@ajhodges , I think the Android implementation works well to track the active routes whenever I tested it.   It should probably be tightened to the 15 minutes and crossing the 1/4 hour threshold also.

**Comment by austin9350** [comment] 2017-03-27 10:00
I implemented a fix for this (branch "routeCacheFix"). 

It invalidates the cache either:
a) after 15 minutes of wall clock time
b) when a quarter-hour boundary has been crossed

I'm planning to test when the trolleys are running this weekend. If all looks good I'll push out a public update. 
If anyone is interested in testing I can put out a TestFlight build.

**Comment by bikeoid** [comment] 2017-03-27 10:45
Yaaay - many thanks, and I'll test it!

**Comment by jeremywight** [comment] 2017-03-27 11:02
I'll test it as well Austin

**Comment by austin9350** [comment] 2017-03-28 01:15
Are your Github email addresses good to send the TestFlight invitations to?

**Comment by bikeoid** [comment] 2017-03-28 02:23
Yes, I think that's my Apple store Email

**Comment by jeremywight** [comment] 2017-03-28 10:06
Yep

**Comment by bikeoid** [comment] 2017-04-01 23:40
I had opened the new app several times when the trolley wasn't running and checked the schedule.  All seemed well.   Today (Saturday) whenever I try to open it, it flashes 2 trolleys, then closes.   Does it send a crash report or is there something else I need to do?

**Comment by austin9350** [comment] 2017-04-02 00:23
Threading bug! I was able to reproduce, I'm doing a new build now. Thanks for the heads up!

**Comment by bikeoid** [comment] 2017-04-02 00:40
That fixed it here - thanks!

**Comment by bikeoid** [comment] 2017-04-04 23:36
Sorry for the delayed report, but I noticed a small problem remaining over the weekend after the switchover at 6:00PM.    At about 4:00 I had looked at the app, then exited the app by pressing Home.  Then went back into the app after 6:15.   I waited about a minute but the old route was still shown.  I checked the schedule with the schedule button, and immediately after pressing the Map button, the route updated.

**Comment by bikeoid** [comment] 2017-06-02 14:02
The current beta on the Test Flight app has expired.

**Comment by austin9350** [comment] 2017-06-03 16:30
I'm uploading a new TF build now

**Comment by austin9350** [comment] 2017-06-03 16:31
I do have a fix in-progress for the issue you mentioned on April 4, but I've been slammed with work and other side projects so I've been a bit slack in getting that finished up...

**Comment by bikeoid** [comment] 2017-06-03 23:51
The Test Flight build is back, thanks!

**Closed** 2023-06-30 15:00 UTC
